apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whatsmypasswd-ingress
  namespace: whatsmypasswd
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
    - host: whatsmypasswd.nks.stjeong.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: whatsmypasswd-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: whatsmypasswd-frontend
                port:
                  number: 80
  # Uncomment for TLS
  # tls:
  #   - hosts:
  #       - passwd.example.com
  #     secretName: whatsmypasswd-tls
