apiVersion: v1
kind: Secret
metadata:
  name: whatsmypasswd-secret
  namespace: whatsmypasswd
type: Opaque
stringData:
  MASTER_PASSWORD: "changeme"
  SECRET_KEY: "your-jwt-secret-key-min-32-chars-long"
  ENCRYPTION_KEY: "your-aes256-encryption-key-min-32-chars"
